[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
fuji = "https://api.avax-test.network/ext/bc/C/rpc"
avalanche = "https://api.avax.network/ext/bc/C/rpc"

# [etherscan]
# fuji = { key = "${SNOWTRACE_API_KEY}", url = "https://api-testnet.snowtrace.io/api" }
# avalanche = { key = "${SNOWTRACE_API_KEY}", url = "https://api.snowtrace.io/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
